# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Devel/ASTInterpreter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Devel/ASTInterpreter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /mnt/d/Devel/ASTInterpreter/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Devel/ASTInterpreter/CMakeFiles /mnt/d/Devel/ASTInterpreter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Devel/ASTInterpreter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arduino_ast_interpreter

# Build rule for target.
arduino_ast_interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arduino_ast_interpreter
.PHONY : arduino_ast_interpreter

# fast build rule for target.
arduino_ast_interpreter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/build
.PHONY : arduino_ast_interpreter/fast

#=============================================================================
# Target rules for targets named test_ast_nodes

# Build rule for target.
test_ast_nodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ast_nodes
.PHONY : test_ast_nodes

# fast build rule for target.
test_ast_nodes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast_nodes.dir/build.make CMakeFiles/test_ast_nodes.dir/build
.PHONY : test_ast_nodes/fast

#=============================================================================
# Target rules for targets named test_compact_ast

# Build rule for target.
test_compact_ast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_compact_ast
.PHONY : test_compact_ast

# fast build rule for target.
test_compact_ast/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_compact_ast.dir/build.make CMakeFiles/test_compact_ast.dir/build
.PHONY : test_compact_ast/fast

#=============================================================================
# Target rules for targets named test_command_protocol

# Build rule for target.
test_command_protocol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_command_protocol
.PHONY : test_command_protocol

# fast build rule for target.
test_command_protocol/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_command_protocol.dir/build.make CMakeFiles/test_command_protocol.dir/build
.PHONY : test_command_protocol/fast

#=============================================================================
# Target rules for targets named test_interpreter_integration

# Build rule for target.
test_interpreter_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_interpreter_integration
.PHONY : test_interpreter_integration

# fast build rule for target.
test_interpreter_integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_interpreter_integration.dir/build.make CMakeFiles/test_interpreter_integration.dir/build
.PHONY : test_interpreter_integration/fast

#=============================================================================
# Target rules for targets named test_cross_platform_validation

# Build rule for target.
test_cross_platform_validation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cross_platform_validation
.PHONY : test_cross_platform_validation

# fast build rule for target.
test_cross_platform_validation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cross_platform_validation.dir/build.make CMakeFiles/test_cross_platform_validation.dir/build
.PHONY : test_cross_platform_validation/fast

#=============================================================================
# Target rules for targets named cross_platform_validation

# Build rule for target.
cross_platform_validation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cross_platform_validation
.PHONY : cross_platform_validation

# fast build rule for target.
cross_platform_validation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cross_platform_validation.dir/build.make CMakeFiles/cross_platform_validation.dir/build
.PHONY : cross_platform_validation/fast

libs/CompactAST/src/CompactAST.o: libs/CompactAST/src/CompactAST.cpp.o
.PHONY : libs/CompactAST/src/CompactAST.o

# target to build an object file
libs/CompactAST/src/CompactAST.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/libs/CompactAST/src/CompactAST.cpp.o
.PHONY : libs/CompactAST/src/CompactAST.cpp.o

libs/CompactAST/src/CompactAST.i: libs/CompactAST/src/CompactAST.cpp.i
.PHONY : libs/CompactAST/src/CompactAST.i

# target to preprocess a source file
libs/CompactAST/src/CompactAST.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/libs/CompactAST/src/CompactAST.cpp.i
.PHONY : libs/CompactAST/src/CompactAST.cpp.i

libs/CompactAST/src/CompactAST.s: libs/CompactAST/src/CompactAST.cpp.s
.PHONY : libs/CompactAST/src/CompactAST.s

# target to generate assembly for a file
libs/CompactAST/src/CompactAST.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/libs/CompactAST/src/CompactAST.cpp.s
.PHONY : libs/CompactAST/src/CompactAST.cpp.s

src/cpp/ASTInterpreter.o: src/cpp/ASTInterpreter.cpp.o
.PHONY : src/cpp/ASTInterpreter.o

# target to build an object file
src/cpp/ASTInterpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ASTInterpreter.cpp.o
.PHONY : src/cpp/ASTInterpreter.cpp.o

src/cpp/ASTInterpreter.i: src/cpp/ASTInterpreter.cpp.i
.PHONY : src/cpp/ASTInterpreter.i

# target to preprocess a source file
src/cpp/ASTInterpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ASTInterpreter.cpp.i
.PHONY : src/cpp/ASTInterpreter.cpp.i

src/cpp/ASTInterpreter.s: src/cpp/ASTInterpreter.cpp.s
.PHONY : src/cpp/ASTInterpreter.s

# target to generate assembly for a file
src/cpp/ASTInterpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ASTInterpreter.cpp.s
.PHONY : src/cpp/ASTInterpreter.cpp.s

src/cpp/ASTNodes.o: src/cpp/ASTNodes.cpp.o
.PHONY : src/cpp/ASTNodes.o

# target to build an object file
src/cpp/ASTNodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ASTNodes.cpp.o
.PHONY : src/cpp/ASTNodes.cpp.o

src/cpp/ASTNodes.i: src/cpp/ASTNodes.cpp.i
.PHONY : src/cpp/ASTNodes.i

# target to preprocess a source file
src/cpp/ASTNodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ASTNodes.cpp.i
.PHONY : src/cpp/ASTNodes.cpp.i

src/cpp/ASTNodes.s: src/cpp/ASTNodes.cpp.s
.PHONY : src/cpp/ASTNodes.s

# target to generate assembly for a file
src/cpp/ASTNodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ASTNodes.cpp.s
.PHONY : src/cpp/ASTNodes.cpp.s

src/cpp/ArduinoDataTypes.o: src/cpp/ArduinoDataTypes.cpp.o
.PHONY : src/cpp/ArduinoDataTypes.o

# target to build an object file
src/cpp/ArduinoDataTypes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ArduinoDataTypes.cpp.o
.PHONY : src/cpp/ArduinoDataTypes.cpp.o

src/cpp/ArduinoDataTypes.i: src/cpp/ArduinoDataTypes.cpp.i
.PHONY : src/cpp/ArduinoDataTypes.i

# target to preprocess a source file
src/cpp/ArduinoDataTypes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ArduinoDataTypes.cpp.i
.PHONY : src/cpp/ArduinoDataTypes.cpp.i

src/cpp/ArduinoDataTypes.s: src/cpp/ArduinoDataTypes.cpp.s
.PHONY : src/cpp/ArduinoDataTypes.s

# target to generate assembly for a file
src/cpp/ArduinoDataTypes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ArduinoDataTypes.cpp.s
.PHONY : src/cpp/ArduinoDataTypes.cpp.s

src/cpp/ArduinoLibraryRegistry.o: src/cpp/ArduinoLibraryRegistry.cpp.o
.PHONY : src/cpp/ArduinoLibraryRegistry.o

# target to build an object file
src/cpp/ArduinoLibraryRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ArduinoLibraryRegistry.cpp.o
.PHONY : src/cpp/ArduinoLibraryRegistry.cpp.o

src/cpp/ArduinoLibraryRegistry.i: src/cpp/ArduinoLibraryRegistry.cpp.i
.PHONY : src/cpp/ArduinoLibraryRegistry.i

# target to preprocess a source file
src/cpp/ArduinoLibraryRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ArduinoLibraryRegistry.cpp.i
.PHONY : src/cpp/ArduinoLibraryRegistry.cpp.i

src/cpp/ArduinoLibraryRegistry.s: src/cpp/ArduinoLibraryRegistry.cpp.s
.PHONY : src/cpp/ArduinoLibraryRegistry.s

# target to generate assembly for a file
src/cpp/ArduinoLibraryRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ArduinoLibraryRegistry.cpp.s
.PHONY : src/cpp/ArduinoLibraryRegistry.cpp.s

src/cpp/CommandProtocol.o: src/cpp/CommandProtocol.cpp.o
.PHONY : src/cpp/CommandProtocol.o

# target to build an object file
src/cpp/CommandProtocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/CommandProtocol.cpp.o
.PHONY : src/cpp/CommandProtocol.cpp.o

src/cpp/CommandProtocol.i: src/cpp/CommandProtocol.cpp.i
.PHONY : src/cpp/CommandProtocol.i

# target to preprocess a source file
src/cpp/CommandProtocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/CommandProtocol.cpp.i
.PHONY : src/cpp/CommandProtocol.cpp.i

src/cpp/CommandProtocol.s: src/cpp/CommandProtocol.cpp.s
.PHONY : src/cpp/CommandProtocol.s

# target to generate assembly for a file
src/cpp/CommandProtocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/CommandProtocol.cpp.s
.PHONY : src/cpp/CommandProtocol.cpp.s

src/cpp/EnhancedInterpreter.o: src/cpp/EnhancedInterpreter.cpp.o
.PHONY : src/cpp/EnhancedInterpreter.o

# target to build an object file
src/cpp/EnhancedInterpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/EnhancedInterpreter.cpp.o
.PHONY : src/cpp/EnhancedInterpreter.cpp.o

src/cpp/EnhancedInterpreter.i: src/cpp/EnhancedInterpreter.cpp.i
.PHONY : src/cpp/EnhancedInterpreter.i

# target to preprocess a source file
src/cpp/EnhancedInterpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/EnhancedInterpreter.cpp.i
.PHONY : src/cpp/EnhancedInterpreter.cpp.i

src/cpp/EnhancedInterpreter.s: src/cpp/EnhancedInterpreter.cpp.s
.PHONY : src/cpp/EnhancedInterpreter.s

# target to generate assembly for a file
src/cpp/EnhancedInterpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/EnhancedInterpreter.cpp.s
.PHONY : src/cpp/EnhancedInterpreter.cpp.s

src/cpp/ExecutionTracer.o: src/cpp/ExecutionTracer.cpp.o
.PHONY : src/cpp/ExecutionTracer.o

# target to build an object file
src/cpp/ExecutionTracer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ExecutionTracer.cpp.o
.PHONY : src/cpp/ExecutionTracer.cpp.o

src/cpp/ExecutionTracer.i: src/cpp/ExecutionTracer.cpp.i
.PHONY : src/cpp/ExecutionTracer.i

# target to preprocess a source file
src/cpp/ExecutionTracer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ExecutionTracer.cpp.i
.PHONY : src/cpp/ExecutionTracer.cpp.i

src/cpp/ExecutionTracer.s: src/cpp/ExecutionTracer.cpp.s
.PHONY : src/cpp/ExecutionTracer.s

# target to generate assembly for a file
src/cpp/ExecutionTracer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arduino_ast_interpreter.dir/build.make CMakeFiles/arduino_ast_interpreter.dir/src/cpp/ExecutionTracer.cpp.s
.PHONY : src/cpp/ExecutionTracer.cpp.s

tests/test_ast_nodes.o: tests/test_ast_nodes.cpp.o
.PHONY : tests/test_ast_nodes.o

# target to build an object file
tests/test_ast_nodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast_nodes.dir/build.make CMakeFiles/test_ast_nodes.dir/tests/test_ast_nodes.cpp.o
.PHONY : tests/test_ast_nodes.cpp.o

tests/test_ast_nodes.i: tests/test_ast_nodes.cpp.i
.PHONY : tests/test_ast_nodes.i

# target to preprocess a source file
tests/test_ast_nodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast_nodes.dir/build.make CMakeFiles/test_ast_nodes.dir/tests/test_ast_nodes.cpp.i
.PHONY : tests/test_ast_nodes.cpp.i

tests/test_ast_nodes.s: tests/test_ast_nodes.cpp.s
.PHONY : tests/test_ast_nodes.s

# target to generate assembly for a file
tests/test_ast_nodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ast_nodes.dir/build.make CMakeFiles/test_ast_nodes.dir/tests/test_ast_nodes.cpp.s
.PHONY : tests/test_ast_nodes.cpp.s

tests/test_command_protocol.o: tests/test_command_protocol.cpp.o
.PHONY : tests/test_command_protocol.o

# target to build an object file
tests/test_command_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_command_protocol.dir/build.make CMakeFiles/test_command_protocol.dir/tests/test_command_protocol.cpp.o
.PHONY : tests/test_command_protocol.cpp.o

tests/test_command_protocol.i: tests/test_command_protocol.cpp.i
.PHONY : tests/test_command_protocol.i

# target to preprocess a source file
tests/test_command_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_command_protocol.dir/build.make CMakeFiles/test_command_protocol.dir/tests/test_command_protocol.cpp.i
.PHONY : tests/test_command_protocol.cpp.i

tests/test_command_protocol.s: tests/test_command_protocol.cpp.s
.PHONY : tests/test_command_protocol.s

# target to generate assembly for a file
tests/test_command_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_command_protocol.dir/build.make CMakeFiles/test_command_protocol.dir/tests/test_command_protocol.cpp.s
.PHONY : tests/test_command_protocol.cpp.s

tests/test_compact_ast.o: tests/test_compact_ast.cpp.o
.PHONY : tests/test_compact_ast.o

# target to build an object file
tests/test_compact_ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_compact_ast.dir/build.make CMakeFiles/test_compact_ast.dir/tests/test_compact_ast.cpp.o
.PHONY : tests/test_compact_ast.cpp.o

tests/test_compact_ast.i: tests/test_compact_ast.cpp.i
.PHONY : tests/test_compact_ast.i

# target to preprocess a source file
tests/test_compact_ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_compact_ast.dir/build.make CMakeFiles/test_compact_ast.dir/tests/test_compact_ast.cpp.i
.PHONY : tests/test_compact_ast.cpp.i

tests/test_compact_ast.s: tests/test_compact_ast.cpp.s
.PHONY : tests/test_compact_ast.s

# target to generate assembly for a file
tests/test_compact_ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_compact_ast.dir/build.make CMakeFiles/test_compact_ast.dir/tests/test_compact_ast.cpp.s
.PHONY : tests/test_compact_ast.cpp.s

tests/test_cross_platform_validation.o: tests/test_cross_platform_validation.cpp.o
.PHONY : tests/test_cross_platform_validation.o

# target to build an object file
tests/test_cross_platform_validation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cross_platform_validation.dir/build.make CMakeFiles/test_cross_platform_validation.dir/tests/test_cross_platform_validation.cpp.o
.PHONY : tests/test_cross_platform_validation.cpp.o

tests/test_cross_platform_validation.i: tests/test_cross_platform_validation.cpp.i
.PHONY : tests/test_cross_platform_validation.i

# target to preprocess a source file
tests/test_cross_platform_validation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cross_platform_validation.dir/build.make CMakeFiles/test_cross_platform_validation.dir/tests/test_cross_platform_validation.cpp.i
.PHONY : tests/test_cross_platform_validation.cpp.i

tests/test_cross_platform_validation.s: tests/test_cross_platform_validation.cpp.s
.PHONY : tests/test_cross_platform_validation.s

# target to generate assembly for a file
tests/test_cross_platform_validation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cross_platform_validation.dir/build.make CMakeFiles/test_cross_platform_validation.dir/tests/test_cross_platform_validation.cpp.s
.PHONY : tests/test_cross_platform_validation.cpp.s

tests/test_interpreter_integration.o: tests/test_interpreter_integration.cpp.o
.PHONY : tests/test_interpreter_integration.o

# target to build an object file
tests/test_interpreter_integration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_interpreter_integration.dir/build.make CMakeFiles/test_interpreter_integration.dir/tests/test_interpreter_integration.cpp.o
.PHONY : tests/test_interpreter_integration.cpp.o

tests/test_interpreter_integration.i: tests/test_interpreter_integration.cpp.i
.PHONY : tests/test_interpreter_integration.i

# target to preprocess a source file
tests/test_interpreter_integration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_interpreter_integration.dir/build.make CMakeFiles/test_interpreter_integration.dir/tests/test_interpreter_integration.cpp.i
.PHONY : tests/test_interpreter_integration.cpp.i

tests/test_interpreter_integration.s: tests/test_interpreter_integration.cpp.s
.PHONY : tests/test_interpreter_integration.s

# target to generate assembly for a file
tests/test_interpreter_integration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_interpreter_integration.dir/build.make CMakeFiles/test_interpreter_integration.dir/tests/test_interpreter_integration.cpp.s
.PHONY : tests/test_interpreter_integration.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cross_platform_validation"
	@echo "... arduino_ast_interpreter"
	@echo "... test_ast_nodes"
	@echo "... test_command_protocol"
	@echo "... test_compact_ast"
	@echo "... test_cross_platform_validation"
	@echo "... test_interpreter_integration"
	@echo "... libs/CompactAST/src/CompactAST.o"
	@echo "... libs/CompactAST/src/CompactAST.i"
	@echo "... libs/CompactAST/src/CompactAST.s"
	@echo "... src/cpp/ASTInterpreter.o"
	@echo "... src/cpp/ASTInterpreter.i"
	@echo "... src/cpp/ASTInterpreter.s"
	@echo "... src/cpp/ASTNodes.o"
	@echo "... src/cpp/ASTNodes.i"
	@echo "... src/cpp/ASTNodes.s"
	@echo "... src/cpp/ArduinoDataTypes.o"
	@echo "... src/cpp/ArduinoDataTypes.i"
	@echo "... src/cpp/ArduinoDataTypes.s"
	@echo "... src/cpp/ArduinoLibraryRegistry.o"
	@echo "... src/cpp/ArduinoLibraryRegistry.i"
	@echo "... src/cpp/ArduinoLibraryRegistry.s"
	@echo "... src/cpp/CommandProtocol.o"
	@echo "... src/cpp/CommandProtocol.i"
	@echo "... src/cpp/CommandProtocol.s"
	@echo "... src/cpp/EnhancedInterpreter.o"
	@echo "... src/cpp/EnhancedInterpreter.i"
	@echo "... src/cpp/EnhancedInterpreter.s"
	@echo "... src/cpp/ExecutionTracer.o"
	@echo "... src/cpp/ExecutionTracer.i"
	@echo "... src/cpp/ExecutionTracer.s"
	@echo "... tests/test_ast_nodes.o"
	@echo "... tests/test_ast_nodes.i"
	@echo "... tests/test_ast_nodes.s"
	@echo "... tests/test_command_protocol.o"
	@echo "... tests/test_command_protocol.i"
	@echo "... tests/test_command_protocol.s"
	@echo "... tests/test_compact_ast.o"
	@echo "... tests/test_compact_ast.i"
	@echo "... tests/test_compact_ast.s"
	@echo "... tests/test_cross_platform_validation.o"
	@echo "... tests/test_cross_platform_validation.i"
	@echo "... tests/test_cross_platform_validation.s"
	@echo "... tests/test_interpreter_integration.o"
	@echo "... tests/test_interpreter_integration.i"
	@echo "... tests/test_interpreter_integration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

